const weatherIcons: { [key: string]: { [key: string]: string } } = {
  "dark-mode": {
    "01d": "/public/images/weather_icons/dark-mode/icon_01d.png",
    "01n": "/public/images/weather_icons/dark-mode/icon_01n.png",
    "02d": "/public/images/weather_icons/dark-mode/icon_02d.png",
    "02n": "/public/images/weather_icons/dark-mode/icon_02n.png",
    "03d": "/public/images/weather_icons/dark-mode/icon_03d.png",
    "03n": "/public/images/weather_icons/dark-mode/icon_03n.png",
    "04d": "/public/images/weather_icons/dark-mode/icon_04d.png",
    "04n": "/public/images/weather_icons/dark-mode/icon_04n.png",
    "09d": "/public/images/weather_icons/dark-mode/icon_09d.png",
    "09n": "/public/images/weather_icons/dark-mode/icon_09n.png",
    "10d": "/public/images/weather_icons/dark-mode/icon_10d.png",
    "10n": "/public/images/weather_icons/dark-mode/icon_10n.png",
    "11d": "/public/images/weather_icons/dark-mode/icon_11d.png",
    "11n": "/public/images/weather_icons/dark-mode/icon_11n.png",
    "13d": "/public/images/weather_icons/dark-mode/icon_13d.png",
    "13n": "/public/images/weather_icons/dark-mode/icon_13n.png",
    "50d": "/public/images/weather_icons/dark-mode/icon_50d.png",
    "50n": "/public/images/weather_icons/dark-mode/icon_50n.png",
  },
  "light-mode": {
    "01d": "/public/images/weather_icons/light-mode/icon_01d.png",
    "01n": "/public/images/weather_icons/light-mode/icon_01n.png",
    "02d": "/public/images/weather_icons/light-mode/icon_02d.png",
    "02n": "/public/images/weather_icons/light-mode/icon_02n.png",
    "03d": "/public/images/weather_icons/light-mode/icon_03d.png",
    "03n": "/public/images/weather_icons/light-mode/icon_03n.png",
    "04d": "/public/images/weather_icons/light-mode/icon_04d.png",
    "04n": "/public/images/weather_icons/light-mode/icon_04n.png",
    "09d": "/public/images/weather_icons/light-mode/icon_09d.png",
    "09n": "/public/images/weather_icons/light-mode/icon_09n.png",
    "10d": "/public/images/weather_icons/light-mode/icon_10d.png",
    "10n": "/public/images/weather_icons/light-mode/icon_10n.png",
    "11d": "/public/images/weather_icons/light-mode/icon_11d.png",
    "11n": "/public/images/weather_icons/light-mode/icon_11n.png",
    "13d": "/public/images/weather_icons/light-mode/icon_13d.png",
    "13n": "/public/images/weather_icons/light-mode/icon_13n.png",
    "50d": "/public/images/weather_icons/light-mode/icon_50d.png",
    "50n": "/public/images/weather_icons/light-mode/icon_50n.png",
  },
};

export default weatherIcons;
